version: '2'
services: 
    nginx: 
        build: ./nginx
        ports: 
            - "80:80"
        volumes:
            - ./web:/src
        networks:
            - backend
    fpm:
        image: php:fpm-alpine
        volumes:
            - ./web:/src
        networks:
            - backend

    dev:
        build: .
        volumes:
            - ./web:/src
            - /src/node_modules
networks:
    backend:
